spring.application.name=GatewayService

# Server Configuration
server.port=8080

# Spring Cloud Gateway Routes
# Route 1: Auth Service
spring.cloud.gateway.routes[0].id=AuthService
spring.cloud.gateway.routes[0].uri=lb://AuthService
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=AuthService
spring.cloud.gateway.routes[1].uri=lb://AuthService
spring.cloud.gateway.routes[1].predicates[0]=Path=/customer/**


# Route 2: User Service
#spring.cloud.gateway.routes[1].id=user-service
#spring.cloud.gateway.routes[1].uri=lb://user-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=TzAE2BGlLBg/RePhdclHkba/cOXRHHVfoQdO3r1umsY=
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000